### ISSUE TITLE
NSInternalInconsistencyException when userTapped func called

### ISSUE THREAD

**Issue by gbmiranda** [rob-nash/CollapsableTable-Swift#2]
The only difference from the sample project is that I'm not using storyboard.

When I click to expand the section is the error below:

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to insert row 0 into section 1, but there are only 0 rows in section 1 after the update'

**Comment by rob-nash** [comment]
Could you give me access to your source code ?

**Comment by rob-nash** [comment]
Any more information would be great.
