### ISSUE TITLE
Running Problem

### ISSUE THREAD

**Issue by cimbo92** [rob-nash/CollapsableTable-Swift#3]
I don't know how to solve the fact that I can't generate this in my storyBoard. I read that for iOS 8.x and later versions you can't do that anymore. What should I do? Thank you in advance
![screen shot 2015-12-09 at 19 14 04](https://cloud.githubusercontent.com/assets/16178361/11694257/48fa4b2e-9ea9-11e5-8f20-84c59fd1cb67.png)

**Comment by rob-nash** [comment]
You want to know how to build a table view ?
