### ISSUE TITLE
Problem with the orientation 

### ISSUE THREAD

**Issue by cimbo92** [rob-nash/CollapsableTable-Swift#4]
When I turn my device the first and the last cell of my subsections are cutted. What can I do? Thank you in advance 
![screen shot 2015-12-09 at 19 23 14](https://cloud.githubusercontent.com/assets/16178361/11694431/59b6eab6-9eaa-11e5-983d-67362980ed67.png)

**Comment by rob-nash** [comment]
If you are using my xib, which it seems like you are, then the height for that xib is 76.0f.

-(CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section {
    return 76.0f;
}
