### ISSUE TITLE
How to change items

### ISSUE THREAD

**Issue by ysnsyhn** [rob-nash/CollapsableTable-Swift#5]
![items](https://cloud.githubusercontent.com/assets/9936311/12402839/5865aa1e-be38-11e5-85cc-cdae9bc9eec2.jpg)

How to change the the items below the main titles which are marked in the image.
How to add it and make it clickable. Even explain how to do it or add it in the code pls.

**Comment by hanappaula** [comment]
Hi,

What I've done was remove this function from ViewController:
```
override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        return tableView.dequeueReusableCellWithIdentifier("Cell")!
    }
```

And on CollapsableTableScene class I edited  this function like this:

```
public func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let item = self.model()?[indexPath.section].items[indexPath.row] as! String
        let cell = UITableViewCell(style: UITableViewCellStyle.Value1, reuseIdentifier: nil)
        cell.textLabel?.text = item
        return cell
    }
```

I don't know if this is the best solution but it's what worked for me :)

**Comment by ysnsyhn** [comment]
@hanappaula Thank you very much. It solved my problem :+1:

**Comment by craigpearce5** [comment]
@ysnsyhn If @hanappaula solved your problem, you should close the issue.

**Comment by rob-nash** [comment]
Sorry guys, I closed this issue without making a comment. I should mention that what you have done is fine, but your subclass should be responsible for introducing the specialised functionality that you want your specify implementation to perform.

So rather than modifying the library, just override the methods that the library exposes. So for example

```
override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let text = self.myModel[indexPath.section].items[indexPath.row] as! String
        let cell = tableView.dequeueReusableCellWithIdentifier("Cell")!
        cell.textLabel?.text = text
        return cell
}
```
