### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by shahdhiren** [rob-nash/CollapsableTable-Swift#6]
Current implementation expects separate XIB file for the UITableViewHeader. Can we have option for UIView as well? I am asking for the feature because, currently Storyboard do supports the UIView to be separate from ViewController. Hence it would be better to have UIView within storyboard rather than creating separate file for the same. Hence, utilizing more features of Storyboard

Hope this will help to others as well.

**Comment by rob-nash** [comment]
You should avoiding having all of your logic in one place. Especially, considering that storyboards are XML, which is painful to use when working in a team and multiple team members want to work on the same piece of UI. 

In addition to that, auto-layout can be quite challenging when all of your UI is in one place. Having smaller files for handling specific areas of your UI, is probably the best approach for keeping your focus small and your source control commits, even smaller.

Sorry.
