### ISSUE TITLE
Cannot remove arrow when no items

### ISSUE THREAD

**Issue by tomgekeerd** [rob-nash/CollapsableTable-Swift#7]
Am I correct it is currently not possible to remove the arrow when you don't have any items on that particular section?

**Comment by rob-nash** [comment]
Think about how you would handle this situation in a table view that doesn't use this library. Then apply that same logic to your current implementation of this library.

https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/TableView_iPhone/ManageInsertDeleteRow/ManageInsertDeleteRow.html

For the record, the demo App in this repo has an arrow animation to indicate the open/closed state of a table view section and your own implementation of this library does not require the same animation.
